spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1     
    
            - id: MENTOR-SERVICE
              uri: lb://mentor-service
              predicates:
                - Path=/mentor-service/**
              filters:
                - StripPrefix=1     
    
            - id: USER-SERVICE
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1     
    
            - id: SESSION-SERVICE
              uri: lb://session-service
              predicates:
                - Path=/session-service/**
              filters:
                - StripPrefix=1
    
            - id: REVIEW-SERVICE
              uri: lb://review-service
              predicates:
                - Path=/review-service/**
              filters:
                - StripPrefix=1
                
            - id: SKILL-SERVICE
              uri: lb://skill-service
              predicates:
                - Path=/skill-service/**
              filters:
                - StripPrefix=1


server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
      gateway:
        enabled: true 
  endpoints:
    web:
      exposure:
        include: "*"      
  springdoc:
    api-docs:
      enable: true
    swagger-ui:
      config-url: /v3/api-docs/swagger-config
      disable-swagger-default-url: true
