spring:
  application:
    name: api-gateway

  cloud:
    discovery:
      enabled: true

    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**

        - id: MENTOR-SERVICE
          uri: lb://mentor-service
          predicates:
            - Path=/mentor-service/**

        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: SESSION-SERVICE
          uri: lb://session-service
          predicates:
            - Path=/session-service/**
          filters:
            - StripPrefix=1

        - id: REVIEW-SERVICE
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1

        - id: SKILL-SERVICE
          uri: lb://skill-service
          predicates:
            - Path=/skill-service/**

        - id: NOTIFICATION-SERVICE
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth-service/v3/api-docs
      - name: Mentor Service
        url: /mentor-service/v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Session Service
        url: /session-service/v3/api-docs
      - name: Review Service
        url: /review-service/v3/api-docs
      - name: Skill Service
        url: /skill-service/v3/api-docs
      - name: Notification Service
        url: /notification-service/v3/api-docs

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
